version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped

  redis:
    image: redis:7.0.4-alpine
    restart: unless-stopped
    env_file: .env
    command: redis-server --bind 0.0.0.0 --port 6379
    ports:
      - "6379:6379"


